name: Auto Release

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Every day at midnight

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Configure Git identity
        run: |
          git config --global user.name "release-bot"
          git config --global user.email "release-bot@github.com"

      - name: Pull latest main branch
        run: git pull origin main --rebase

      - name: Run release-it
        id: release
        run: |
          npx release-it --ci --git.tagForce
        continue-on-error: true

      - name: Push release changes
        if: ${{ success() }}
        run: |
          git push origin main --tags
