name: Auto Release

on:
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: "*/1 * * * *" # Every 5 minutes

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Configure Git identity
        run: |
          git config --global user.name "release-bot"
          git config --global user.email "release-bot@github.com"

      - name: Pull latest main branch
        run: git pull origin main --rebase

      - name: Run release-it
        run: npx release-it --ci --git.tagForce
